### ISSUE TITLE
No linux support

### ISSUE THREAD

**Issue by dogenkigen** [Johnnei/JavaTorrent#32]
There is no option to run this app on linux, but it could be. I think it can be simply added by changing Config.getFile method to

private void getFile(String filename) {
		String os = System.getProperty("os.name");
		String home = System.getProperty("user.home");
		if (os.equals("Linux")) {
			folder = home + "/JavaTorrent/";
			new File(folder).mkdirs();
		} else {
			folder = home + "\\";
		}

		if (os.equals("Windows 7") || os.equals("Windows Vista")) {
			folder += "AppData\\Roaming\\JavaTorrent\\";
			new File(folder).mkdirs();
		}

		configFile = new File(folder + filename);
		if (!configFile.exists()) {
			try {
				configFile.createNewFile();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}

**Comment by Johnnei** [comment]
This problem will be resolved in the gui repo as it only affects the GUI side after the refactoring.
